"""Find illegal moves being generated by checking king safety."""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from engine.board import Board, decode_move
from engine.moves import Moves, is_square_attacked, find_king_square

def check_all_moves_legal(board: Board, depth_limit=3, current_depth=0):
    """Recursively check all generated moves are truly legal."""
    if current_depth >= depth_limit:
        return 0
    
    illegal_count = 0
    moves_gen = Moves(board)
    legal_moves = moves_gen.generate()
    
    for move in legal_moves:
        # Make the move
        undo_info = board.make_move(move)
        
        # The king that just moved should NOT be in check
        # (The side that made the move is now 1 - current_side)
        current_side = board.current_player.value
        previous_side = 1 - current_side
        
        # Find the king of the side that just moved
        king_sq = find_king_square(board.state, previous_side)
        
        # Check if that king is attacked by the current side
        if is_square_attacked(board.state, king_sq, current_side):
            illegal_count += 1
            from_sq, to_sq, flags = decode_move(move)
            print(f"✗ ILLEGAL MOVE at depth {current_depth}:")
            print(f"  Move: {from_sq}->{to_sq} (flags={flags})")
            print(f"  Position: {board.to_fen()}")
            print(f"  King at {king_sq} is in check!")
            print()
        
        # Recurse
        illegal_count += check_all_moves_legal(board, depth_limit, current_depth + 1)
        
        # Unmake
        board.unmake_move(move, undo_info)
    
    return illegal_count

def main():
    fen = "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1"
    board = Board(fen=fen)
    
    print("Checking for illegal moves in Kiwipete (depth 3)")
    print("="*80)
    
    illegal = check_all_moves_legal(board, depth_limit=3)
    
    print("="*80)
    print(f"Total illegal moves found: {illegal}")
    
    if illegal == 0:
        print("✓ All moves are legal!")
        print("The perft discrepancy must be elsewhere...")
    else:
        print("✗ Found illegal moves being generated!")

if __name__ == '__main__':
    main()
